site_name: eQual framework 
site_url: https://doc.equal.run/
docs_dir: docs
# dev_addr: 127.0.0.1:8000
repo_name: equal
repo_url: https://github.com/equalframework/equal
edit_uri: ""
theme:
  name: material
  favicon: '_assets/img/favicon.png'
  logo: '_assets/img/eq_logo.png'
  feature:
    tabs: true
  features: 
    - navigation.instant  
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - '_assets/css/extra.css'
plugins:
  - search  
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
extra:
  version:
    provider: mike
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Welcome': 
      - 'eQual': 'index.md'
      - 'Release notes': 'welcome/release-notes.md'
      - 'Choose your path': 'welcome/choose-path.md'
      - 'Contribute': 'welcome/contribute.md'
  - 'Application Developpers':
      - 'Getting Started':
          - 'Installation': 'application-developpers/getting-started/installation.md'
          - 'Quick Start': 'application-developpers/getting-started/quick-start.md'
          - 'Deployment': 'application-developpers/getting-started/deployment.md'
          - 'Configuration': 'application-developpers/getting-started/configuration.md'
      - 'Core Development Guide':
          - 'Models (Entities / Actions / Workflows)':
               - 'Actions': 'application-developpers/core-development-guide/models/actions.md'
               - 'Entities': 'application-developpers/core-development-guide/models/entities.md'
               - 'Workflows': 'application-developpers/core-development-guide/models/workflows.md'
               - 'Authorization':
                     - 'Authorization Concepts': 'application-developpers/core-development-guide/models/authorization/authorization-overview.md'
                     - 'Authentication': 'application-developpers/core-development-guide/models/authorization/authentication.md'
                     - 'Access Control Lists': 'application-developpers/core-development-guide/models/authorization/access-control-lists.md'
                     - 'Passkeys': 'application-developpers/core-development-guide/models/authorization/passkeys.md'
               - 'Collections':
                     - 'Collections Overview': 'application-developpers/core-development-guide/models/collections/collections-overview.md'
                     - 'Collection Special Architectures': 'application-developpers/core-development-guide/models/collections/collections-special-architectures.md'
                     - 'Collection Usage': 'application-developpers/core-development-guide/models/collections/collections-usage.md'
                     - 'Collection Best Practices': 'application-developpers/core-development-guide/models/collections/collections-best-practices.md'
               - 'Data Anonymization': 'application-developpers/core-development-guide/models/data-anonymization.md'
               - 'Data Import': 'application-developpers/core-development-guide/models/data-import.md'
               - 'Domains': 'application-developpers/core-development-guide/models/domains.md'
               - 'Entities':
                     - 'Entities Overview': 'application-developpers/core-development-guide/models/entities/entities.md'
                     - 'Fields': 'application-developpers/core-development-guide/models/entities/fields.md'
                     - 'Computed Fields': 'application-developpers/core-development-guide/models/entities/computed-fields.md'
                     - 'Seeding': 'application-developpers/core-development-guide/models/entities/seeding.md'
               - 'Model Factory': 'application-developpers/core-development-guide/models/model-factory.md'
               - 'Operations': 'application-developpers/core-development-guide/models/operations.md'
               - 'ORM': 'application-developpers/core-development-guide/models/orm.md'
               - 'Programming Paradigm': 'application-developpers/core-development-guide/models/programming-paradigm.md'
               - 'Workflows': 
                     - 'Workflows Overview': 'application-developpers/core-development-guide/models/workflows/workflows.md'
                     - 'Tasks': 'application-developpers/core-development-guide/models/workflows/tasks.md'
               - 'Services': 'application-developpers/core-development-guide/models/services.md'
          - 'Views & UI': 
               - 'Views':
                     - 'Common Structures': 
                        - 'Common Structures Overview': 'application-developpers/core-development-guide/views-ui/views/common-structures/common-structures.md'
                        - 'Views & Actions' : 'application-developpers/core-development-guide/views-ui/views/common-structures/views-actions.md'
                     - 'Forms' : 'application-developpers/core-development-guide/views-ui/views/forms.md'
                     - 'Lists' : 'application-developpers/core-development-guide/views-ui/views/lists.md'
                     - 'Widgets' : 'application-developpers/core-development-guide/views-ui/views/widgets.md'
                     - 'Charts' : 'application-developpers/core-development-guide/views-ui/views/charts.md'
                     - 'Dashboards' : 'application-developpers/core-development-guide/views-ui/views/dashboards.md'
               - 'Inheritence' : 'application-developpers/core-development-guide/views-ui/inheritence.md'
               - 'Frontend logic': 'application-developpers/core-development-guide/views-ui/frontend-logic.md'
               - 'Menus' : 'application-developpers/core-development-guide/views-ui/menus.md'
               - 'Contexts': 'application-developpers/core-development-guide/views-ui/contexts.md'
               - 'Low-Code Overview': 'application-developpers/core-development-guide/views-ui/low-code-overview.md'
          - 'Validation & Searching': 
                - 'Validation': 'application-developpers/core-development-guide/validation-searching/validation.md'
                - 'Searching': 'application-developpers/core-development-guide/validation-searching/searching.md'
                - 'JSON Schemas': 'application-developpers/core-development-guide/validation-searching/json-schemas.md'
          - 'Internationalization':
                - 'Internationalization Overview': 'application-developpers/core-development-guide/i18n/i18n-overview.md'
                - 'Interface': 'application-developpers/core-development-guide/i18n/i18n-interface.md'
                - 'Model Data': 'application-developpers/core-development-guide/i18n/i18n-model-data.md'
          - 'Controllers & Routing':
                - 'Controllers': 'application-developpers/core-development-guide/controllers-routing/controllers.md'
                - 'Routing': 'application-developpers/core-development-guide/controllers-routing/routing.md'
      - 'How-Tos & Reference':
          - 'Tutorials / Examples': 
                - 'Tutorial: Using the Workbench': 'application-developpers/howtos-references/tutorials-examples/tutorial-building-simple-app.md'
                - 'Tutorial: Creating a ReST API': 'application-developpers/howtos-references/tutorials-examples/tutorial-rest-api.md'
                - 'Tutorial: A basic WebApp' : 'application-developpers/howtos-references/tutorials-examples/tutorial-basic-webapp.md'
                - 'Example: A basic Controller' : 'application-developpers/howtos-references/tutorials-examples/example-basic-controller.md'
                - 'Example: Domains': 'application-developpers/howtos-references/tutorials-examples/example-domain.md'
                - 'Example: Shared-lib Code Snippets': 'application-developpers/howtos-references/tutorials-examples/shared-lib-code-snippets.md'
          - 'Cheat Sheets': 'application-developpers/howtos-references/cheat-sheet.md'
          - 'API / CLI Reference': 'application-developpers/howtos-references/api-cli.md' 
          - 'Package': 'application-developpers/howtos-references/package.md'
          - 'Using Shared-lib': 'application-developpers/howtos-references/using-shared-lib.md'
          - 'Workbench Overview' : 'application-developpers/howtos-references/workbench-overview.md'
      - 'AI guidelines ??': ''
  - 'Operations (DevOps / Sysadmin)':
      - 'Deployment & Environment':
          - 'Server setup': 'operations\deployment-environment\server-setup.md'
          - 'CI/CD': 'operations\deployment-environment\ci-cd.md'
          - 'PHP compatibility': 'operations\deployment-environment\php-compatibility.md'
          - 'Installation & Config Utilities': 'operations/deployment-environment/installation-config-utilities.md'
          - 'Package Utilities': 'operations/deployment-environment/package-utilities.md'
          - 'Shared-lib Setup': 'operations/deployment-environment/shared-lib-setup.md'
      - 'Database & Storage':
          - 'Database administration': ''  
          - 'Backup / Restore': ''   
          - 'Data Manipulation Utilities': 'operations/database-storage/data-manipulation-utilities.md'
      - 'Monitoring & Maintenance':
          - 'Rights Management Utilities': 'operations/monitoring-maintenance/rights-management-utilities.md'
          - 'Logging': ''
          - 'Performance': '' 
          - 'Upgrades': ''  
  - 'Community (Core / Contributors)':
      - 'Contribution Guide':
          - 'Coding standards': ''
          - 'PR workflow': ''
          - 'Tests & coverage': ''
      - 'Internal Architecture':
          - 'Framework internals': ''
          - 'Framework internals': 'community/internal-architecture/framework-internals.md'
          - 'Design principles': ''
  - 'Help & Support':
      - 'Troubleshooting & Diagnostics':
          - 'Common issues': ''
          - 'Debugging tools': ''
      - 'Logging & Error Handling':
          - 'Logs structure': ''
          - 'Error codes': ''
      - 'Contact & Support':
          - 'Report a bug': ''
          - 'Support channels': ''
          - 'Security disclosure': ''